---
title: "SAS THESIS"
author: Sara Garza Gonzalez
output: html_document
date: "2025-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load packages, include=FALSE}
library(tinytex)
library(readr)
library(readxl)
library(data.table)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lme4)
library(ggpubr)
library(psych)
library(rcompanion)
library(coin)
library(ggplotgui)
library(table1)
library(supernova)
library(pROC)
library(broom)
library(glmnet)
library(rpart)
library(rpart.plot)
library(ggpattern)
library(lmerTest)

```

```{r, truncating speaker time series}

#set wd for speakers
setwd("~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/speaker_brain/")

SS02_A <- read.csv("SS02_A.csv", header = FALSE)
SS02_A <-SS02_A[-c(1:12), ]

SS11_B <- read.csv("SS11_B.csv", header = FALSE)
SS11_B <- SS11_B[-c(1:4), ]

SS12_C <- read.csv("SS12_C.csv", header = FALSE)
SS12_C <- SS12_C[-c(1:31), ]

SS15_D  <- read.csv("SS15_D.csv", header = FALSE)
SS15_D <- SS15_D[-c(1:157), ] #SL056_D only has 605 rows, so adjusting to this one

SS18_E <- read.csv("SS18_E.csv", header = FALSE)
SS18_E <- SS18_E[-c(1:84), ]

SS19_F <- read.csv("SS19_F.csv", header = FALSE)

SS23_G <- read.csv("SS23_G.csv", header = FALSE)
SS23_G <- SS23_G[-c(1:8), ] #SL036_G only has 918 rows, so adjusting to this one

SS24_H <- read.csv("SS24_H.csv", header = FALSE)
SS24_H <- SS24_H[-c(1:57), ] #SL056_H only has 1260 rows, so adjusting to this one

SS30_I <- read.csv("SS30_I.csv", header = FALSE)
SS30_I <- SS30_I[-c(1:23), ]

SS31_J <- read.csv("SS31_J.csv", header = FALSE)
SS31_J <- SS31_J[-c(1:4), ]

SS33_K <- read.csv("SS33_K.csv", header = FALSE)
SS33_K <- SS33_K[-c(1:65), ]

SS34_L <- read.csv("SS34_L.csv", header = FALSE)

SS41_M <- read.csv("SS41_M.csv", header = FALSE)
SS41_M <- SS41_M[-c(1:8), ]

SS42_N <- read.csv("SS42_N.csv", header = FALSE)
SS42_N <- SS42_N[-c(1:12), ]

```

```{r, make all column names the same for all speaker data frames}

colnames(SS02_A) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS11_B) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS12_C) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS15_D) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS18_E) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS19_F) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS23_G) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS24_H) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS30_I) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS31_J) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS33_K) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS34_L) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

colnames(SS41_M) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")


colnames(SS42_N) <- c("ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8", "ch9", "ch10", "ch11", "ch12", "ch13", "ch14", "ch15", "ch16", "ch17", "ch18", "ch19", "ch20", "ch21", "ch22", "ch23", "ch24", "ch25", "ch26", "ch27", "ch28", "ch29", "ch30", "ch31", "ch32", "ch33", "ch34", "ch35", "ch36", "ch37", "ch38","ch39", "ch40", "ch41", "ch42", "ch43", "ch44", "ch45", "ch46", "ch47", "ch48", "ch49", "ch50", "ch51", "ch52", "ch53", "ch54", "ch55", "ch56", "ch57", "ch58", "ch59", "ch60", "ch61", "ch62", "ch63", "ch64", "ch65", "ch66", "ch67", "ch68", "ch69", "ch70", "ch71", "ch72", "ch73", "ch74", "ch75", "ch76", "ch77", "ch78", "ch79", "ch80", "ch81", "ch82", "ch83", "ch84", "ch85", "ch86", "ch87", "ch88", "ch89", "ch90", "ch91", "ch92", "ch93", "ch94", "ch95", "ch96", "ch97", "ch98", "ch99", "ch100")

```

```{r, make all column names the same for all listener data frames}

# List all CSV files explicitly (case-insensitive match)
file_list <- list.files(path = "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/", pattern = "(?i)\\.csv$", full.names = TRUE)

# Print the list of found CSV files (for debugging)
print(file_list)

# Function to read CSV files and change column names
ChangeNamesAndRead <- function(file) {
  df <- read_csv(file, show_col_types = FALSE)
  
  # Change column names
  colnames(df) <- paste0("ch", 1:ncol(df))
  
  return(df)
}

# Loop through each file and assign the resulting data frame to the global environment
for (i in seq_along(file_list)) {
  file_name <- file_list[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_name <- tools::file_path_sans_ext(basename(file_name))
  
  # Read and change column names
  df <- ChangeNamesAndRead(file_name)
  
  # Assign the dataframe to the global environment
  assign(df_name, df, envir = .GlobalEnv)
}

```

```{r, trimming all listeners A data frames to match Speaker A}

# Set the directory containing your data files
data_dirA <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listA <- list.files(path = data_dirA, pattern = "(?i)A.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker A" dataframe
speaker_A_row_count <- nrow(SS02_A)

# Now loop through each listener file and trim to match the row count of "Speaker A"
for (i in seq_along(file_listA)) {
  file_nameA <- file_listA[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameA <- tools::file_path_sans_ext(basename(file_nameA))
  
  # Read the listener data
  listener_dataA <- ChangeNamesAndRead(file_nameA)
  
  # Trim listener data to match the row count of Speaker A
  if (nrow(listener_dataA) >= speaker_A_row_count) {
    trimmed_listener_dataA <- listener_dataA[1:speaker_A_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker A. No trimming applied."))
    trimmed_listener_dataA <- listener_dataA
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameA, trimmed_listener_dataA, envir = .GlobalEnv)
}

```

```{r, trimming all listeners B data frames to match Speaker B}

# Set the directory containing your data files
data_dirB <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly that have "B" in their name (case-insensitive match)
file_listB <- list.files(path = data_dirB, pattern = "(?i)B.*\\.csv$", full.names = TRUE)

# Print the list of found files (for debugging)
print(file_listB)

# Get the number of rows in the "Speaker B" dataframe
speaker_B_row_count <- nrow(SS11_B)

# Now loop through each listener file and trim to match the row count of "Speaker B"
for (i in seq_along(file_listB)) {
  file_nameB <- file_listB[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameB <- tools::file_path_sans_ext(basename(file_nameB))
  
  # Read the listener data
  listener_dataB <- ChangeNamesAndRead(file_nameB)
  
  # Trim listener data to match the row count of Speaker B
  if (nrow(listener_dataB) >= speaker_B_row_count) {
    trimmed_listener_dataB <- listener_dataB[1:speaker_B_row_count, ]
  } else {
    warning(paste("Listener data", df_nameB, "has fewer rows than Speaker B. No trimming applied."))
    trimmed_listener_dataB <- listener_dataB
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameB, trimmed_listener_dataB, envir = .GlobalEnv)
}

```

```{r, trimming all listeners C data frames to match Speaker C}

# Set the directory containing your data files
data_dirC <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listC <- list.files(path = data_dirC, pattern = "(?i)C.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker C" dataframe
speaker_C_row_count <- nrow(SS12_C)

# Now loop through each listener file and trim to match the row count of "Speaker C"
for (i in seq_along(file_listC)) {
  file_nameC <- file_listC[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameC <- tools::file_path_sans_ext(basename(file_nameC))
  
  # Read the listener data
  listener_dataC <- ChangeNamesAndRead(file_nameC)
  
  # Trim listener data to match the row count of Speaker C
  if (nrow(listener_dataC) >= speaker_C_row_count) {
    trimmed_listener_dataC <- listener_dataC[1:speaker_C_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker C. No trimming applied."))
    trimmed_listener_dataC <- listener_dataC
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameC, trimmed_listener_dataC, envir = .GlobalEnv)
}

```

```{r, trimming all listeners D data frames to match Speaker D}

# Set the directory containing your data files
data_dirD <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listD <- list.files(path = data_dirD, pattern = "(?i)D.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker D" dataframe
speaker_D_row_count <- nrow(SS15_D)

# Now loop through each listener file and trim to match the row count of "Speaker D"
for (i in seq_along(file_listD)) {
  file_nameD <- file_listD[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameD <- tools::file_path_sans_ext(basename(file_nameD))
  
  # Read the listener data
  listener_dataD <- ChangeNamesAndRead(file_nameD)
  
  # Trim listener data to match the row count of Speaker D
  if (nrow(listener_dataD) >= speaker_D_row_count) {
    trimmed_listener_dataD <- listener_dataC[1:speaker_D_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker D. No trimming applied."))
    trimmed_listener_dataD <- listener_dataD
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameD, trimmed_listener_dataD, envir = .GlobalEnv)
}

```

```{r, trimming all listeners E data frames to match Speaker E}

# Set the directory containing your data files
data_dirE <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listE <- list.files(path = data_dirE, pattern = "(?i)E.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker E" dataframe
speaker_E_row_count <- nrow(SS18_E)

# Now loop through each listener file and trim to match the row count of "Speaker E"
for (i in seq_along(file_listE)) {
  file_nameE <- file_listE[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameE <- tools::file_path_sans_ext(basename(file_nameE))
  
  # Read the listener data
  listener_dataE <- ChangeNamesAndRead(file_nameE)
  
  # Trim listener data to match the row count of Speaker E
  if (nrow(listener_dataE) >= speaker_E_row_count) {
    trimmed_listener_dataE <- listener_dataE[1:speaker_E_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker E. No trimming applied."))
    trimmed_listener_dataE <- listener_dataE
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameE, trimmed_listener_dataE, envir = .GlobalEnv)
}

```

```{r, trimming all listeners F data frames to match Speaker F}

# Set the directory containing your data files
data_dirF <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listF <- list.files(path = data_dirF, pattern = "(?i)F.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker F" dataframe
speaker_F_row_count <- nrow(SS19_F)

# Now loop through each listener file and trim to match the row count of "Speaker F"
for (i in seq_along(file_listF)) {
  file_nameF <- file_listF[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameF <- tools::file_path_sans_ext(basename(file_nameF))
  
  # Read the listener data
  listener_dataF <- ChangeNamesAndRead(file_nameF)
  
  # Trim listener data to match the row count of Speaker D
  if (nrow(listener_dataF) >= speaker_F_row_count) {
    trimmed_listener_dataF <- listener_dataF[1:speaker_F_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker F. No trimming applied."))
    trimmed_listener_dataF <- listener_dataF
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameF, trimmed_listener_dataF, envir = .GlobalEnv)
}

```

```{r, trimming all listeners G data frames to match Speaker G}

# Set the directory containing your data files
data_dirG <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List all CSV files explicitly (case-insensitive match)
file_listG <- list.files(path = data_dirF, pattern = "(?i)G.*\\.csv$", full.names = TRUE)

#Get the number of rows in the "Speaker G" dataframe
speaker_G_row_count <- nrow(SS23_G)

# Now loop through each listener file and trim to match the row count of "Speaker G"
for (i in seq_along(file_listG)) {
  file_nameG <- file_listG[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameG <- tools::file_path_sans_ext(basename(file_nameG))
  
  # Read the listener data
  listener_dataG <- ChangeNamesAndRead(file_nameG)
  
  # Trim listener data to match the row count of Speaker G
  if (nrow(listener_dataG) >= speaker_G_row_count) {
    trimmed_listener_dataG <- listener_dataG[1:speaker_G_row_count, ]
  } else {
    warning(paste("Listener data", df_name, "has fewer rows than Speaker G. No trimming applied."))
    trimmed_listener_dataG <- listener_dataG
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameG, trimmed_listener_dataG, envir = .GlobalEnv)
}

```

```{r, trimming all listeners H data frames to match Speaker H}

# Set the directory containing your data files
data_dirH <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener H 
file_listH <- list.files(path = data_dirH, pattern = "(?i)SL[0-9]{3}_H\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker H" dataframe
speaker_H_row_count <- nrow(SS24_H)

# Now loop through each listener file and trim to match the row count of "Speaker H"
for (i in seq_along(file_listH)) {
  file_nameH <- file_listH[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameH <- tools::file_path_sans_ext(basename(file_nameH))
  
  # Read the listener data
  listener_dataH <- ChangeNamesAndRead(file_nameH)
  
  # Trim listener data to match the row count of Speaker H
  if (nrow(listener_dataH) >= speaker_H_row_count) {
    trimmed_listener_dataH <- listener_dataH[1:speaker_H_row_count, ]
  } else {
    warning(paste("Listener data", df_nameH, "has fewer rows than Speaker H. No trimming applied."))
    trimmed_listener_dataH <- listener_dataH
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameH, trimmed_listener_dataH, envir = .GlobalEnv)
}

```

```{r, trimming all listeners I data frames to match Speaker I}

# Set the directory containing your data files
data_dirI <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener I 
file_listI <- list.files(path = data_dirI, pattern = "(?i)SL[0-9]{3}_I\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker I" dataframe
speaker_I_row_count <- nrow(SS30_I)

# Now loop through each listener file and trim to match the row count of "Speaker I"
for (i in seq_along(file_listI)) {
  file_nameI <- file_listI[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameI <- tools::file_path_sans_ext(basename(file_nameI))
  
  # Read the listener data
  listener_dataI <- ChangeNamesAndRead(file_nameI)
  
  # Trim listener data to match the row count of Speaker I
  if (nrow(listener_dataI) >= speaker_I_row_count) {
    trimmed_listener_dataI <- listener_dataI[1:speaker_I_row_count, ]
  } else {
    warning(paste("Listener data", df_nameI, "has fewer rows than Speaker I. No trimming applied."))
    trimmed_listener_dataI <- listener_dataI
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameI, trimmed_listener_dataI, envir = .GlobalEnv)
}

```

```{r, trimming all listeners J data frames to match Speaker J}

# Set the directory containing your data files
data_dirJ <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener J 
file_listJ <- list.files(path = data_dirJ, pattern = "(?i)SL[0-9]{3}_J\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker J" dataframe
speaker_J_row_count <- nrow(SS31_J)

# Now loop through each listener file and trim to match the row count of "Speaker J"
for (i in seq_along(file_listJ)) {
  file_nameJ <- file_listJ[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameJ <- tools::file_path_sans_ext(basename(file_nameJ))
  
  # Read the listener data
  listener_dataJ <- ChangeNamesAndRead(file_nameJ)
  
  # Trim listener data to match the row count of Speaker J
  if (nrow(listener_dataJ) >= speaker_J_row_count) {
    trimmed_listener_dataJ <- listener_dataJ[1:speaker_J_row_count, ]
  } else {
    warning(paste("Listener data", df_nameJ, "has fewer rows than Speaker J. No trimming applied."))
    trimmed_listener_dataJ <- listener_dataJ
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameJ, trimmed_listener_dataJ, envir = .GlobalEnv)
}

```

```{r, trimming all listeners K data frames to match Speaker K}

# Set the directory containing your data files
data_dirK <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener K 
file_listK <- list.files(path = data_dirK, pattern = "(?i)SL[0-9]{3}_K\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker K" dataframe
speaker_K_row_count <- nrow(SS33_K)

# Now loop through each listener file and trim to match the row count of "Speaker K"
for (i in seq_along(file_listK)) {
  file_nameK <- file_listK[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameK <- tools::file_path_sans_ext(basename(file_nameK))
  
  # Read the listener data
  listener_dataK <- ChangeNamesAndRead(file_nameK)
  
  # Trim listener data to match the row count of Speaker K
  if (nrow(listener_dataK) >= speaker_K_row_count) {
    trimmed_listener_dataK <- listener_dataK[1:speaker_K_row_count, ]
  } else {
    warning(paste("Listener data", df_nameK, "has fewer rows than Speaker K. No trimming applied."))
    trimmed_listener_dataK <- listener_dataK
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameK, trimmed_listener_dataK, envir = .GlobalEnv)
}

```

```{r, trimming all listeners L data frames to match Speaker L}

# Set the directory containing your data files
data_dirL <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener L 
file_listL <- list.files(path = data_dirL, pattern = "(?i)SL[0-9]{3}_L\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker L" dataframe
speaker_L_row_count <- nrow(SS34_L)

# Now loop through each listener file and trim to match the row count of "Speaker L"
for (i in seq_along(file_listL)) {
  file_nameL <- file_listL[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameL <- tools::file_path_sans_ext(basename(file_nameL))
  
  # Read the listener data
  listener_dataL <- ChangeNamesAndRead(file_nameL)
  
  # Trim listener data to match the row count of Speaker L
  if (nrow(listener_dataL) >= speaker_L_row_count) {
    trimmed_listener_dataL <- listener_dataL[1:speaker_L_row_count, ]
  } else {
    warning(paste("Listener data", df_nameL, "has fewer rows than Speaker L. No trimming applied."))
    trimmed_listener_dataL <- listener_dataL
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameL, trimmed_listener_dataL, envir = .GlobalEnv)
}

```

```{r, trimming all listeners M data frames to match Speaker M}

# Set the directory containing your data files
data_dirM <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener M 
file_listM <- list.files(path = data_dirM, pattern = "(?i)SL[0-9]{3}_M\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker M" dataframe
speaker_M_row_count <- nrow(SS41_M)

# Now loop through each listener file and trim to match the row count of "Speaker M"
for (i in seq_along(file_listM)) {
  file_nameM <- file_listM[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameM <- tools::file_path_sans_ext(basename(file_nameM))
  
  # Read the listener data
  listener_dataM <- ChangeNamesAndRead(file_nameM)
  
  # Trim listener data to match the row count of Speaker M
  if (nrow(listener_dataM) >= speaker_M_row_count) {
    trimmed_listener_dataM <- listener_dataM[1:speaker_M_row_count, ]
  } else {
    warning(paste("Listener data", df_nameM, "has fewer rows than Speaker M. No trimming applied."))
    trimmed_listener_dataM <- listener_dataM
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameM, trimmed_listener_dataM, envir = .GlobalEnv)
}

```

```{r, trimming all listeners N data frames to match Speaker N}

# Set the directory containing your data files
data_dirN <- "~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_brain/untitled folder 2/"

# List only files with the exact format for listener N 
file_listN <- list.files(path = data_dirN, pattern = "(?i)SL[0-9]{3}_N\\.csv$", full.names = TRUE)

# Get the number of rows in the "Speaker N" dataframe
speaker_N_row_count <- nrow(SS42_N)

# Now loop through each listener file and trim to match the row count of "Speaker N"
for (i in seq_along(file_listN)) {
  file_nameN <- file_listN[i]
  
  # Get the base file name (without path and extension) to use as the data frame name
  df_nameN <- tools::file_path_sans_ext(basename(file_nameN))
  
  # Read the listener data
  listener_dataN <- ChangeNamesAndRead(file_nameN)
  
  # Trim listener data to match the row count of Speaker N
  if (nrow(listener_dataN) >= speaker_N_row_count) {
    trimmed_listener_dataN <- listener_dataN[1:speaker_N_row_count, ]
  } else {
    warning(paste("Listener data", df_nameN, "has fewer rows than Speaker N. No trimming applied."))
    trimmed_listener_dataN <- listener_dataN
  }
  
  # Assign the trimmed listener data to the global environment
  assign(df_nameN, trimmed_listener_dataN, envir = .GlobalEnv)
}

```

```{r, creating new empty data frame}
dyads_df <- setNames(data.frame(matrix(ncol = 105, nrow = length(file_list))), 
                     c("speaker_id", "listener_id", "video_id", "shared_exp", 
                       paste0("ch", 1:100)))
```

```{r, spearman correlations for Speaker A}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate Spearman's rho and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, method = "spearman", use = "complete.obs")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
  # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS02_A, SL034_A, "SS02_A", "SL034_A", "A", 1)

# Second Dyad
dyads_df <- calculate_correlations(SS02_A, SL040_A, "SS02_A", "SL040_A", "A", 2)

# Third Dyad
dyads_df <- calculate_correlations(SS02_A, SL041_A, "SS02_A", "SL041_A", "A", 3)

# Fourth Dyad
dyads_df <- calculate_correlations(SS02_A, SL051_A, "SS02_A", "SL051_A", "A", 4)

# Fifth Dyad
dyads_df <- calculate_correlations(SS02_A, SL053_A, "SS02_A", "SL053_A", "A", 5)

# Sixth Dyad
dyads_df <- calculate_correlations(SS02_A, SL058_A, "SS02_A", "SL058_A", "A", 6)

# Seventh Dyad
dyads_df <- calculate_correlations(SS02_A, SL068_A, "SS02_A", "SL068_A", "A", 7)

# Eighth Dyad
dyads_df <- calculate_correlations(SS02_A, SL070_A, "SS02_A", "SL070_A", "A", 8)

# Ninth Dyad
dyads_df <- calculate_correlations(SS02_A, SL072_A, "SS02_A", "SL072_A", "A", 9)

```

```{r, spearman correlations for Speaker B}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS11_B, SL030_B, "SS11_B", "SL030_B", "B", 10)

# Second Dyad
dyads_df <- calculate_correlations(SS11_B, SL033_B, "SS11_B", "SL033_B", "B", 11)

# Third Dyad
dyads_df <- calculate_correlations(SS11_B, SL044_B, "SS11_B", "SL044_B", "B", 12)

# Fourth Dyad
dyads_df <- calculate_correlations(SS11_B, SL045_B, "SS11_B", "SL045_B", "B", 13)

# Fifth Dyad
dyads_df <- calculate_correlations(SS11_B, SL065_B, "SS11_B", "SL065_B", "B", 14)

# Sixth Dyad
dyads_df <- calculate_correlations(SS11_B, SL067_B, "SS11_B", "SL067_B", "B", 15)

# Seventh Dyad
dyads_df <- calculate_correlations(SS11_B, SL069_B, "SS11_B", "SL069_B", "B", 16)

# Eighth Dyad
dyads_df <- calculate_correlations(SS11_B, SL070_B, "SS11_B", "SL070_B", "B", 17)

# Ninth Dyad
dyads_df <- calculate_correlations(SS11_B, SL074_B, "SS11_B", "SL074_B", "B", 18)

# Tehth Dyad
dyads_df <- calculate_correlations(SS11_B, SL078_B, "SS11_B", "SL078_B", "B", 19)

```

```{r, spearman correlations for Speaker C}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS12_C, SL029_C, "SS12_C", "SL029_C", "C", 20)

# Second Dyad
dyads_df <- calculate_correlations(SS12_C, SL033_C, "SS12_C", "SL033_C", "C", 21)

# Third Dyad
dyads_df <- calculate_correlations(SS12_C, SL036_C, "SS12_C", "SL036_C", "C", 22)

# Fourth Dyad
dyads_df <- calculate_correlations(SS12_C, SL051_C, "SS12_C", "SL051_C", "C", 23)

# Fifth Dyad
dyads_df <- calculate_correlations(SS12_C, SL052_C, "SS12_C", "SL052_C", "C", 24)

# Sixth Dyad
dyads_df <- calculate_correlations(SS12_C, SL054_C, "SS12_C", "SL054_C", "C", 25)

# Seventh Dyad
dyads_df <- calculate_correlations(SS12_C, SL061_C, "SS12_C", "SL061_C", "C", 26)

# Eighth Dyad
dyads_df <- calculate_correlations(SS12_C, SL063_C, "SS12_C", "SL063_C", "C", 27)

# Ninth Dyad
dyads_df <- calculate_correlations(SS12_C, SL071_C, "SS12_C", "SL071_C", "C", 28)

# Tenth Dyad
dyads_df <- calculate_correlations(SS12_C, SL074_C, "SS12_C", "SL074_C", "C", 29)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS12_C, SL075_C, "SS12_C", "SL075_C", "C", 30)
```

```{r, spearman correlations for Speaker D}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS15_D, SL039_D, "SS15_D", "SL039_D", "D", 31)

# Second Dyad
dyads_df <- calculate_correlations(SS15_D, SL047_D, "SS15_D", "SL047_D", "D", 32)

# Third Dyad
dyads_df <- calculate_correlations(SS15_D, SL050_D, "SS15_D", "SL050_D", "D", 33)

# Fourth Dyad
dyads_df <- calculate_correlations(SS15_D, SL056_D, "SS15_D", "SL056_D", "D", 34)

# Fifth Dyad
dyads_df <- calculate_correlations(SS15_D, SL059_D, "SS15_D", "SL059_D", "D", 35)

# Sixth Dyad
dyads_df <- calculate_correlations(SS15_D, SL064_D, "SS15_D", "SL064_D", "D", 36)

# Seventh Dyad
dyads_df <- calculate_correlations(SS15_D, SL075_D, "SS15_D", "SL075_D", "D", 37)

# Eighth Dyad
dyads_df <- calculate_correlations(SS15_D, SL079_D, "SS15_D", "SL079_D", "D", 38)

```

```{r, spearman correlations for Speaker E}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
# Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS18_E, SL029_E, "SS18_E", "SL029_E", "E", 39)

# Second Dyad
dyads_df <- calculate_correlations(SS18_E, SL032_E, "SS18_E", "SL032_E", "E", 40)

# Third Dyad
dyads_df <- calculate_correlations(SS18_E, SL034_E, "SS18_E", "SL034_E", "E", 41)

# Fourth Dyad
dyads_df <- calculate_correlations(SS18_E, SL045_E, "SS18_E", "SL045_E", "E", 42)

# Fifth Dyad
dyads_df <- calculate_correlations(SS18_E, SL051_E, "SS18_E", "SL051_E", "E", 43)

# Sixth Dyad
dyads_df <- calculate_correlations(SS18_E, SL057_E, "SS18_E", "SL057_E", "E", 44)

# Seventh Dyad
dyads_df <- calculate_correlations(SS18_E, SL058_E, "SS18_E", "SL058_E", "E", 45)

# Eighth Dyad
dyads_df <- calculate_correlations(SS18_E, SL063_E, "SS18_E", "SL063_E", "E", 46)

# Ninth Dyad
dyads_df <- calculate_correlations(SS18_E, SL076_E, "SS18_E", "SL076_E", "E", 47)

```

```{r, spearman correlations for Speaker F}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS19_F, SL033_F, "SS19_F", "SL033_F", "F", 48)

# Second Dyad
dyads_df <- calculate_correlations(SS19_F, SL037_F, "SS19_F", "SL037_F", "F", 49)

# Third Dyad
dyads_df <- calculate_correlations(SS19_F, SL039_F, "SS19_F", "SL039_F", "F", 50)

# Fourth Dyad
dyads_df <- calculate_correlations(SS19_F, SL040_F, "SS19_F", "SL040_F", "F", 51)

# Fifth Dyad
dyads_df <- calculate_correlations(SS19_F, SL041_F, "SS19_F", "SL041_F", "F", 52)

# Sixth Dyad
dyads_df <- calculate_correlations(SS19_F, SL045_F, "SS19_F", "SL045_F", "F", 53)

# Seventh Dyad
dyads_df <- calculate_correlations(SS19_F, SL053_F, "SS19_F", "SL053_F", "F", 54)

# Eighth Dyad
dyads_df <- calculate_correlations(SS19_F, SL056_F, "SS19_F", "SL056_F", "F", 55)

# Ninth Dyad
dyads_df <- calculate_correlations(SS19_F, SL057_F, "SS19_F", "SL057_F", "F", 56)

# Tenth Dyad
dyads_df <- calculate_correlations(SS19_F, SL058_F, "SS19_F", "SL058_F", "F", 57)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS19_F, SL059_F, "SS19_F", "SL059_F", "F", 58)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS19_F, SL061_F, "SS19_F", "SL061_F", "F", 59)

# Twelfth Dyad
dyads_df <- calculate_correlations(SS19_F, SL065_F, "SS19_F", "SL065_F", "F", 60)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS19_F, SL074_F, "SS19_F", "SL074_F", "F", 61)

# Fourteenth Dyad
dyads_df <- calculate_correlations(SS19_F, SL075_F, "SS19_F", "SL075_F", "F", 62)

```

```{r, spearman correlations for Speaker G}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS23_G, SL032_G, "SS23_G", "SL032_G", "G", 63)

# Second Dyad
dyads_df <- calculate_correlations(SS23_G, SL036_G, "SS23_G", "SL036_G", "G", 64)

# Third Dyad
dyads_df <- calculate_correlations(SS23_G, SL038_G, "SS23_G", "SL038_G", "G", 65)

# Fourth Dyad
dyads_df <- calculate_correlations(SS23_G, SL040_G, "SS23_G", "SL040_G", "G", 66)

# Fifth Dyad
dyads_df <- calculate_correlations(SS23_G, SL048_G, "SS23_G", "SL048_G", "G", 67)

# Sixth Dyad
dyads_df <- calculate_correlations(SS23_G, SL052_G, "SS23_G", "SL052_G", "G", 68)

# Seventh Dyad
dyads_df <- calculate_correlations(SS23_G, SL053_G, "SS23_G", "SL053_G", "G", 69)

# Eighth Dyad
dyads_df <- calculate_correlations(SS23_G, SL055_G, "SS23_G", "SL055_G", "G", 70)

# Ninth Dyad
dyads_df <- calculate_correlations(SS23_G, SL056_G, "SS23_G", "SL056_G", "G", 71)

# Tenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL061_G, "SS23_G", "SL061_G", "G", 72)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS23_G, SL067_G, "SS23_G", "SL067_G", "G", 73)

# Twelfth Dyad
dyads_df <- calculate_correlations(SS23_G, SL068_G, "SS23_G", "SL068_G", "G", 74)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL071_G, "SS23_G", "SL071_G", "G", 75)

# Fourteenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL072_G, "SS23_G", "SL072_G", "G", 76)

# Fifteenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL075_G, "SS23_G", "SL075_G", "G", 77)

# Sixteenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL077_G, "SS23_G", "SL077_G", "G", 78)

# Seventeenth Dyad
dyads_df <- calculate_correlations(SS23_G, SL078_G, "SS23_G", "SL078_G", "G", 79)

```

```{r, spearman correlations for Speaker H}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS24_H, SL030_H, "SS24_H", "SL030_H", "H", 80)

# Second Dyad
dyads_df <- calculate_correlations(SS24_H, SL033_H, "SS24_H", "SL033_H", "H", 81)

# Third Dyad
dyads_df <- calculate_correlations(SS24_H, SL034_H, "SS24_H", "SL034_H", "H", 82)

# Fourth Dyad
dyads_df <- calculate_correlations(SS24_H, SL035_H, "SS24_H", "SL035_H", "H", 83)

# Fifth Dyad
dyads_df <- calculate_correlations(SS24_H, SL037_H, "SS24_H", "SL037_H", "H", 84)

# Sixth Dyad
dyads_df <- calculate_correlations(SS24_H, SL038_H, "SS24_H", "SL038_H", "H", 85)

# Seventh Dyad
dyads_df <- calculate_correlations(SS24_H, SL039_H, "SS24_H", "SL039_H", "H", 86)

# Eighth Dyad
dyads_df <- calculate_correlations(SS24_H, SL042_H, "SS24_H", "SL042_H", "H", 87)

# Ninth Dyad
dyads_df <- calculate_correlations(SS24_H, SL053_H, "SS24_H", "SL053_H", "H", 88)

# Tenth Dyad
dyads_df <- calculate_correlations(SS24_H, SL055_H, "SS24_H", "SL055_H", "H", 89)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS24_H, SL056_H, "SS24_H", "SL056_H", "H", 90)

# Twelfth Dyad
dyads_df <- calculate_correlations(SS24_H, SL065_H, "SS24_H", "SL065_H", "H", 91)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS24_H, SL067_H, "SS24_H", "SL067_H", "H", 92)

# Fourteenth Dyad
dyads_df <- calculate_correlations(SS24_H, SL073_H, "SS24_H", "SL073_H", "H", 93)

# Fifteenth Dyad
dyads_df <- calculate_correlations(SS24_H, SL076_H, "SS24_H", "SL076_H", "H", 94)

# Sixteenth Dyad
dyads_df <- calculate_correlations(SS24_H, SL077_H, "SS24_H", "SL077_H", "H", 95)

```

```{r, spearman correlations for Speaker I}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS30_I, SL030_I, "SS30_I", "SL030_I", "I", 96)

# Second Dyad
dyads_df <- calculate_correlations(SS30_I, SL042_I, "SS30_I", "SL042_I", "I", 97)

# Third Dyad
dyads_df <- calculate_correlations(SS30_I, SL048_I, "SS30_I", "SL048_I", "I", 98)

# Fourth Dyad
dyads_df <- calculate_correlations(SS30_I, SL063_I, "SS30_I", "SL063_I", "I", 99)

# Fifth Dyad
dyads_df <- calculate_correlations(SS30_I, SL070_I, "SS30_I", "SL070_I", "I", 100)

# Sixth Dyad
dyads_df <- calculate_correlations(SS30_I, SL071_I, "SS30_I", "SL071_I", "I", 101)

# Seventh Dyad
dyads_df <- calculate_correlations(SS30_I, SL072_I, "SS30_I", "SL072_I", "I", 102)

# Eighth Dyad
dyads_df <- calculate_correlations(SS30_I, SL073_I, "SS30_I", "SL073_I", "I", 103)

# Ninth Dyad
dyads_df <- calculate_correlations(SS30_I, SL079_I, "SS30_I", "SL079_I", "I", 104)

```

```{r, spearman correlations for Speaker J}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS31_J, SL032_J, "SS31_J", "SL032_J", "J", 105)

# Second Dyad
dyads_df <- calculate_correlations(SS31_J, SL035_J, "SS31_J", "SL035_J", "J", 106)

# Third Dyad
dyads_df <- calculate_correlations(SS31_J, SL044_J, "SS31_J", "SL044_J", "J", 107)

# Fourth Dyad
dyads_df <- calculate_correlations(SS31_J, SL051_J, "SS31_J", "SL051_J", "J", 108)

# Fifth Dyad
dyads_df <- calculate_correlations(SS31_J, SL052_J, "SS31_J", "SL052_J", "J", 109)

# Sixth Dyad
dyads_df <- calculate_correlations(SS31_J, SL054_J, "SS31_J", "SL054_J", "J", 110)

# Seventh Dyad
dyads_df <- calculate_correlations(SS31_J, SL061_J, "SS31_J", "SL061_J", "J", 111)

# Eighth Dyad
dyads_df <- calculate_correlations(SS31_J, SL071_J, "SS31_J", "SL071_J", "J", 112)

# Ninth Dyad
dyads_df <- calculate_correlations(SS31_J, SL073_J, "SS31_J", "SL073_J", "J", 113)

# Tenth Dyad
dyads_df <- calculate_correlations(SS31_J, SL074_J, "SS31_J", "SL074_J", "J", 114)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS31_J, SL076_J, "SS31_J", "SL076_J", "J", 115)

# Twelfth Dyad
dyads_df <- calculate_correlations(SS31_J, SL077_J, "SS31_J", "SL077_J", "J", 116)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS31_J, SL078_J, "SS31_J", "SL078_J", "J", 117)

```

```{r, spearman correlations for Speaker K}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS33_K, SL034_K, "SS33_K", "SL034_K", "K", 118)

# Second Dyad
dyads_df <- calculate_correlations(SS33_K, SL037_K, "SS33_K", "SL037_K", "K", 119)

# Third Dyad
dyads_df <- calculate_correlations(SS33_K, SL038_K, "SS33_K", "SL038_K", "K", 120)

# Fourth Dyad
dyads_df <- calculate_correlations(SS33_K, SL040_K, "SS33_K", "SL040_K", "K", 121)

# Fifth Dyad
dyads_df <- calculate_correlations(SS33_K, SL041_K, "SS33_K", "SL041_K", "K", 122)

# Sixth Dyad
dyads_df <- calculate_correlations(SS33_K, SL045_K, "SS33_K", "SL045_K", "K", 123)

# Seventh Dyad
dyads_df <- calculate_correlations(SS33_K, SL046_K, "SS33_K", "SL046_K", "K", 124)

# Eighth Dyad
dyads_df <- calculate_correlations(SS33_K, SL047_K, "SS33_K", "SL047_K", "K", 125)

# Ninth Dyad
dyads_df <- calculate_correlations(SS33_K, SL059_K, "SS33_K", "SL059_K", "K", 126)

# Tenth Dyad
dyads_df <- calculate_correlations(SS33_K, SL064_K, "SS33_K", "SL064_K", "K", 127)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS33_K, SL069_K, "SS33_K", "SL069_K", "K", 128)

```

```{r, spearman correlations for Speaker L}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS34_L, SL032_L, "SS34_L", "SL032_L", "L", 129)

# Second Dyad
dyads_df <- calculate_correlations(SS34_L, SL035_L, "SS34_L", "SL035_L", "L", 130)

# Third Dyad
dyads_df <- calculate_correlations(SS34_L, SL039_L, "SS34_L", "SL039_L", "L", 131)

# Fourth Dyad
dyads_df <- calculate_correlations(SS34_L, SL042_L, "SS34_L", "SL042_L", "L", 132)

# Fifth Dyad
dyads_df <- calculate_correlations(SS34_L, SL044_L, "SS34_L", "SL044_L", "L", 133)

# Sixth Dyad
dyads_df <- calculate_correlations(SS34_L, SL046_L, "SS34_L", "SL046_L", "L", 134)

# Seventh Dyad
dyads_df <- calculate_correlations(SS34_L, SL047_L, "SS34_L", "SL047_L", "L", 135)

# Eighth Dyad
dyads_df <- calculate_correlations(SS34_L, SL054_L, "SS34_L", "SL054_L", "L", 136)

# Ninth Dyad
dyads_df <- calculate_correlations(SS34_L, SL057_L, "SS34_L", "SL057_L", "L", 137)

# Tenth Dyad
dyads_df <- calculate_correlations(SS34_L, SL059_L, "SS34_L", "SL059_L", "L", 138)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS34_L, SL065_L, "SS34_L", "SL065_L", "L", 139)

# Twelfth Dyad
dyads_df <- calculate_correlations(SS34_L, SL068_L, "SS34_L", "SL068_L", "L", 140)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS34_L, SL072_L, "SS34_L", "SL072_L", "L", 141)

# Fourteenth Dyad
dyads_df <- calculate_correlations(SS34_L, SL073_L, "SS34_L", "SL073_L", "L", 142)

```

```{r, spearman correlations for Speaker M}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
  # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS41_M, SL036_M, "SS41_M", "SL036_M", "M", 143)

# Second Dyad
dyads_df <- calculate_correlations(SS41_M, SL038_M, "SS41_M", "SL038_M", "M", 144)

# Third Dyad
dyads_df <- calculate_correlations(SS41_M, SL047_M, "SS41_M", "SL047_M", "M", 145)

# Fourth Dyad
dyads_df <- calculate_correlations(SS41_M, SL050_M, "SS41_M", "SL050_M", "M", 146)

# Fifth Dyad
dyads_df <- calculate_correlations(SS41_M, SL052_M, "SS41_M", "SL052_M", "M", 147)

# Sixth Dyad
dyads_df <- calculate_correlations(SS41_M, SL069_M, "SS41_M", "SL069_M", "M", 148)

# Seventh Dyad
dyads_df <- calculate_correlations(SS41_M, SL076_M, "SS41_M", "SL076_M", "M", 149)

# Eighth Dyad
dyads_df <- calculate_correlations(SS41_M, SL077_M, "SS41_M", "SL077_M", "M", 150)

# Ninth Dyad
dyads_df <- calculate_correlations(SS41_M, SL079_M, "SS41_M", "SL079_M", "M", 151)

```

```{r, spearman correlations for Speaker N}

# Function to calculate correlations and update the dataframe
calculate_correlations <- function(speaker_data, listener_data, speaker_id, listener_id, video_id, dyad_row) {
  # Create a list to store the correlations for each channel pair
  channel_correlations <- list()
  
  # Loop through channels 1 to 100
  for (i in 1:100) {
    # Create channel names ('ch1', 'ch2', ..., 'ch100')
    channel_name <- paste0("ch", i)
    
    # Subset the data for the current channel for both speaker and listener
    speaker_channel_data <- speaker_data[[channel_name]]  # Data for speaker
    listener_channel_data <- listener_data[[channel_name]] # Data for listener
    
    # Check if there are any non-NA values in both speaker and listener channel data
    if (sum(!is.na(speaker_channel_data)) > 0 && sum(!is.na(listener_channel_data)) > 0) {
      # Calculate the correlation and store it in the list, ignoring NAs
      channel_correlations[[channel_name]] <- cor(speaker_channel_data, listener_channel_data, use = "complete.obs", method = "spearman")
    } else {
      # If no valid data for correlation, assign NA to that channel
      channel_correlations[[channel_name]] <- NA
    }
  }
  
  # Convert the list to a vector for easier insertion into the dataframe
  correlations <- unlist(channel_correlations)
  
 # Insert the identifiers and correlation values into the dyad_row
  dyads_df[dyad_row, 1:4] <- c(speaker_id, listener_id, video_id, NA)  # You can replace NA with actual data
  dyads_df[dyad_row, 5:104] <- correlations  # Insert the correlation values into columns 'ch1' to 'ch100'
  
  # Return the updated dataframe
  return(dyads_df)
}

# First Dyad
dyads_df <- calculate_correlations(SS42_N, SL035_N, "SS42_N", "SL035_N", "N", 152)

# Second Dyad
dyads_df <- calculate_correlations(SS42_N, SL036_N, "SS42_N", "SL036_N", "N", 153)

# Third Dyad
dyads_df <- calculate_correlations(SS42_N, SL041_N, "SS42_N", "SL041_N", "N", 154)

# Fourth Dyad
dyads_df <- calculate_correlations(SS42_N, SL042_N, "SS42_N", "SL042_N", "N", 155)

# Fifth Dyad
dyads_df <- calculate_correlations(SS42_N, SL044_N, "SS42_N", "SL044_N", "N", 156)

# Sixth Dyad
dyads_df <- calculate_correlations(SS42_N, SL050_N, "SS42_N", "SL050_N", "N", 157)

# Seventh Dyad
dyads_df <- calculate_correlations(SS42_N, SL057_N, "SS42_N", "SL057_N", "N", 158)

# Eighth Dyad
dyads_df <- calculate_correlations(SS42_N, SL058_N, "SS42_N", "SL058_N", "N", 159)

# Ninth Dyad
dyads_df <- calculate_correlations(SS42_N, SL063_N, "SS42_N", "SL063_N", "N", 160)

# Tenth Dyad
dyads_df <- calculate_correlations(SS42_N, SL064_N, "SS42_N", "SL064_N", "N", 161)

# Eleventh Dyad
dyads_df <- calculate_correlations(SS42_N, SL067_N, "SS42_N", "SL067_N", "N", 162)

# Twelth Dyad
dyads_df <- calculate_correlations(SS42_N, SL068_N, "SS42_N", "SL068_N", "N", 163)

# Thirteenth Dyad
dyads_df <- calculate_correlations(SS42_N, SL069_N, "SS42_N", "SL069_N", "N", 164)

```

```{r, data cleaning for shared experience, alexithymia scores, and ADHD scores}

#Renaming data frame and filtering for people who completed the study, as well as specific variables of interest
Storytelling_Study_Listeners_March_10_2025_11_07 <- read_csv("~/Library/CloudStorage/Box-Box/MICLab/projects/Storytelling_Study/data/listener_behavioral/Storytelling Study - Listeners_March 10, 2025_11.07.csv")

shared_exp <- Storytelling_Study_Listeners_March_10_2025_11_07 %>%
  filter(Finished == TRUE) %>%
  select(ID, vids, simA_1, simexpB_1, simexpC_1, simexpD_1, simexpE_1, simexpF_1, simexpG_1, 
         simexpH_1, simexpI_1, simexpJ_1, simexpK_1, simexpL_1, simexpM_1, simexpN_1, 
         TAS_1, TAS_2, TAS_3, TAS_4, TAS_5, TAS_6, TAS_7, TAS_8, TAS_9, TAS_10, TAS_11, 
         TAS_12, TAS_13, TAS_14, TAS_15, TAS_16, TAS_17, TAS_18, TAS_19, TAS_20, ADHD_1, ADHD_2, ADHD_3,
         ADHD_4, ADHD_5, ADHD_6, ADHD_7, ADHD_8, ADHD_9, ADHD_10, ADHD_11, ADHD_12, ADHD_13, ADHD_14, ADHD_15,
         ADHD_16, ADHD_17, ADHD_18, age, gender, race, SES)

#delete old data from shared_exp data frame
shared_exp <- shared_exp[-(1:39), ]

#Recoding all values to numeric forms for shared experience variable 
recode <-  c("Strongly disagree" = 1, "Moderately disagree" = 2, "Slightly disagree" = 3, "Neither agree nor disagree" = 4, "Slightly agree" = 5, "Moderately agree" = 6, "Strongly agree" = 7) 

# List of variables for recoding shared experience 
shared_exp_vars <- c("simA_1", "simexpB_1", "simexpC_1", "simexpD_1", "simexpE_1", 
                    "simexpF_1", "simexpG_1", "simexpH_1", "simexpI_1", "simexpJ_1", 
                    "simexpK_1", "simexpL_1", "simexpM_1", "simexpN_1")

#Rewriting shared experience variable to  the recoded version of this variable
for (var in shared_exp_vars) {
  shared_exp[[var]] <- recode[shared_exp[[var]]]
}

#Recoding values to numeric forms for alexithymia variable 
recode2 <-  c("Strongly disagree" = 1, "Disagree moderately" = 2, "Disagree a little" = 3, "Neither agree nor disagree" = 4, "Agree a little" = 5, "Agree moderately" = 6, "Strongly agree" = 7) 

#List of variables for recoding alexithymia
alexi_vars <- c("TAS_1", "TAS_2", "TAS_3", "TAS_6", "TAS_7", "TAS_8", "TAS_9", "TAS_11", 
                "TAS_12", "TAS_13", "TAS_14", "TAS_15", "TAS_16", "TAS_17", "TAS_20")

#Recoding values to numeric forms for alexithymia items that are negatively keyed 
recode3 <-  c("Strongly disagree" = 7, "Disagree moderately" = 6, "Disagree a little" = 5, "Neither agree nor disagree" = 4, "Agree a little" = 3, "Agree moderately" = 2, "Strongly agree" = 1)

#List of variables for recoding alexithymia items that are negatively keyed
alexi_vars2 <- c("TAS_4", "TAS_5", "TAS_10", "TAS_18", "TAS_19")

#Rewriting alexithymia variable to  the recoded version of this variable
for (var in alexi_vars) {
  shared_exp[[var]] <- recode2[shared_exp[[var]]]
}

for (var in alexi_vars2) {
  shared_exp[[var]] <- recode3[shared_exp[[var]]]
}

#Calculating a Composite TAS Score
shared_exp$TASscore <- rowSums(shared_exp[,c("TAS_1", "TAS_2", "TAS_3", "TAS_6", "TAS_7", "TAS_8", "TAS_9", "TAS_11", "TAS_12", "TAS_13", "TAS_14", "TAS_15", "TAS_16", "TAS_17", "TAS_20", "TAS_4", "TAS_5", "TAS_10", "TAS_18", "TAS_19")], na.rm = TRUE)
shared_exp$TASscore[shared_exp$TASscore == 0] <- NA

#Recoding all values to numeric forms for ADHD variable 
recode4 <-  c("Never" = 0, "Rarely" = 1, "Sometimes" = 2, "Often" = 3, "Very often" = 4) 

# List of variables for recoding shared experience 
ADHD_vars <- c("ADHD_1", "ADHD_2", "ADHD_3", "ADHD_4", "ADHD_5", "ADHD_6", "ADHD_7", 
               "ADHD_8", "ADHD_9", "ADHD_10", "ADHD_11", "ADHD_12", "ADHD_13", 
               "ADHD_14", "ADHD_15", "ADHD_16", "ADHD_17", "ADHD_18")

#Rewriting ADHD variable to  the recoded version of this variable
for (var in ADHD_vars) {
  shared_exp[[var]] <- recode4[shared_exp[[var]]]
}

#Calculating a Composite ADHD Score
shared_exp$ADHDscore <- rowSums(shared_exp[,c("ADHD_1", "ADHD_2", "ADHD_3", "ADHD_4", "ADHD_5", "ADHD_6", "ADHD_7", "ADHD_8", "ADHD_9", "ADHD_10", "ADHD_11", "ADHD_12", "ADHD_13", "ADHD_14", "ADHD_15", "ADHD_16", "ADHD_17", "ADHD_18")], na.rm = TRUE)
shared_exp$ADHDscore[shared_exp$ADHDscore == 0] <- NA

#Calculating a PART A ADHD Score
shared_exp$ADHDscoreA <- rowSums(shared_exp[,c("ADHD_1", "ADHD_2", "ADHD_3", "ADHD_4", "ADHD_5", "ADHD_6")], na.rm = TRUE)
shared_exp$ADHDscoreA[shared_exp$ADHDscoreA == 0] <- NA

#Calculating a PART B ADHD Score
shared_exp$ADHDscoreB <- rowSums(shared_exp[,c("ADHD_7", "ADHD_8", "ADHD_9", "ADHD_10", "ADHD_11", "ADHD_12", "ADHD_13", "ADHD_14", "ADHD_15", "ADHD_16", "ADHD_17", "ADHD_18")], na.rm = TRUE)
shared_exp$ADHDscoreB[shared_exp$ADHDscoreB == 0] <- NA

# Extract the numeric part from dyads_df$listener_id and shared_exp$ID to put information into original df
dyads_df$listener_id_num <- gsub("[^0-9]", "", dyads_df$listener_id)
shared_exp$ID_num <- gsub("[^0-9]", "", shared_exp$ID)

# Perform the left join using the numeric IDs and include additional variables (age, race, gender, SES)
dyads_df <- dyads_df %>%
  left_join(shared_exp %>%
              select(ID_num, TASscore, ADHDscore, age, race, gender, SES), 
            by = c("listener_id_num" = "ID_num"))

```

```{r, inputting shared experience scores into original data frame since these are repeated}

# Handling shared experience scores for each letter
dyads_df$listener_letter <- gsub(".*_", "", dyads_df$listener_id)  # Extract the letter part

# Renaming variables for consistency
names(shared_exp)[names(shared_exp) == "simA_1"] <- "simexpA_1"

# Loop over letters and assign shared experience scores
for (letter in LETTERS[1:14]) {
  simexp_var <- paste0("simexp", letter, "_1")
  
  if (!simexp_var %in% colnames(shared_exp)) {
    next
  }
  
  temp_df <- shared_exp %>%
    select(ID_num, all_of(simexp_var))
  
  dyads_df <- dyads_df %>%
    left_join(temp_df, by = c("listener_id_num" = "ID_num"))
  
  dyads_df$shared_exp[dyads_df$listener_letter == letter] <- dyads_df[[simexp_var]][dyads_df$listener_letter == letter]
}

```

```{r, writing csv for dyads_df}

write.csv(dyads_df, file = "~/Downloads/dyads_data.csv", row.names = FALSE)

```


```{r, Multilevel, Mixed Effects Model}

#make shared_exp variable numeric
dyads_df$shared_exp <- as.numeric(dyads_df$shared_exp)

# Initialize an empty list to store the models
model_list <- list()

# Loop through channels 1 to 100
for (ch in 1:100) {
  # Dynamically create the formula for each channel
  formula <- as.formula(paste0("ch", ch, " ~ shared_exp * ADHDscore + TASscore + (1 | speaker_id) + (1 | listener_id_num)"))
  
  # Fit the linear mixed effects model
  model_list[[paste0("modelch", ch)]] <- lmer(formula, data = dyads_df)
  
  # Print the summary of the model
  print(paste0("Summary of model for channel ", ch))
  print(summary(model_list[[paste0("modelch", ch)]]))
}

```

```{r, correcting for multiple comparisons for original model}

# Initialize an empty vector to store p-values
p_values <- c()

# Loop through each model in the model list to extract p-values
for (model_name in names(model_list)) {
  # Extract the summary of the model
  summary_model <- summary(model_list[[model_name]])
  
  # Extract the p-value for the interaction term 'shared_exp:ADHDscore'
  p_value <- summary_model$coefficients["shared_exp:ADHDscore", "Pr(>|t|)"]
  
  # Save the p-value in the p_values vector
  p_values <- c(p_values, p_value)
}

# Apply FDR correction to the p-values using p.adjust() function
p_values_fdr_corrected <- p.adjust(p_values, method = "fdr")

# Print the FDR-corrected p-values
print(p_values_fdr_corrected)

```

```{r, model 2 testing for exploratory analyses shared_exp score}

# Initialize an empty list to store the models
model_list2 <- list()

# Loop through channels 1 to 100
for (ch in 1:100) {
  # Dynamically create the formula for each channel
  formula2 <- as.formula(paste0("ch", ch, " ~ shared_exp + (1 | speaker_id) + (1 | listener_id_num)"))
  
  # Fit the linear mixed effects model
  model_list2[[paste0("modelch", ch)]] <- lmer(formula2, data = dyads_df)
  
  # Print the summary of the model
  print(paste0("Summary of model for channel ", ch))
  print(summary(model_list2[[paste0("modelch", ch)]]))
}

# Initialize an empty vector to store p-values
p_values2 <- c()

# Loop through each model in the model list to extract p-values
for (model_name2 in names(model_list2)) {
  # Extract the summary of the model
  summary_model2 <- summary(model_list2[[model_name2]])
  
  # Extract the p-value for shared_exp
  p_value2 <- summary_model2$coefficients["shared_exp", "Pr(>|t|)"]
  
  # Save the p-value in the p_values vector
  p_values2 <- c(p_values2, p_value2)
}

# Apply FDR correction to the p-values using p.adjust() function
p_values_fdr_corrected2 <- p.adjust(p_values2, method = "fdr")

# Print the FDR-corrected p-values
print(p_values_fdr_corrected2)

```

```{r, model 3 testing for exploratory analyses ADHDscore}

# Initialize an empty list to store the models
model_list3 <- list()

# Loop through channels 1 to 100
for (ch in 1:100) {
  # Dynamically create the formula for each channel
  formula3 <- as.formula(paste0("ch", ch, " ~ ADHDscore + (1 | speaker_id) + (1 | listener_id_num)"))
  
  # Fit the linear mixed effects model
  model_list3[[paste0("modelch", ch)]] <- lmer(formula3, data = dyads_df)
  
  # Print the summary of the model
  print(paste0("Summary of model for channel ", ch))
  print(summary(model_list3[[paste0("modelch", ch)]]))
}

# Initialize an empty vector to store p-values
p_values3 <- c()

# Loop through each model in the model list to extract p-values
for (model_name3 in names(model_list3)) {
  # Extract the summary of the model
  summary_model3 <- summary(model_list3[[model_name3]])
  
  # Extract the p-value for ADHDscore'
  p_value3 <- summary_model3$coefficients["ADHDscore", "Pr(>|t|)"]
  
  # Save the p-value in the p_values vector
  p_values3 <- c(p_values3, p_value3)
}

# Apply FDR correction to the p-values using p.adjust() function
p_values_fdr_corrected3 <- p.adjust(p_values3, method = "fdr")

# Print the FDR-corrected p-values
print(p_values_fdr_corrected3)

```

```{r, model 4 testing for exploratory analyses TASscore}

# Initialize an empty list to store the models
model_list4 <- list()

# Loop through channels 1 to 100
for (ch in 1:100) {
  # Dynamically create the formula for each channel
  formula4 <- as.formula(paste0("ch", ch, " ~ TASscore + (1 | speaker_id) + (1 | listener_id_num)"))
  
  # Fit the linear mixed effects model
  model_list4[[paste0("modelch", ch)]] <- lmer(formula4, data = dyads_df)
  
  # Print the summary of the model
  print(paste0("Summary of model for channel ", ch))
  print(summary(model_list4[[paste0("modelch", ch)]]))
}

# Initialize an empty vector to store p-values
p_values4 <- c()

# Loop through each model in the model list to extract p-values
for (model_name4 in names(model_list4)) {
  # Extract the summary of the model
  summary_model4 <- summary(model_list4[[model_name4]])
  
  # Extract the p-value for TASscore'
  p_value4 <- summary_model4$coefficients["TASscore", "Pr(>|t|)"]
  
  # Save the p-value in the p_values vector
  p_values4 <- c(p_values4, p_value4)
}

# Apply FDR correction to the p-values using p.adjust() function
p_values_fdr_corrected4 <- p.adjust(p_values4, method = "fdr")

# Print the FDR-corrected p-values
print(p_values_fdr_corrected4)

```

```{r, demographics cleaning}

mean_age <- mean(dyads_df$age, na.rm = TRUE)
print(mean_age)
sd_age <- sd(dyads_df$age, na.rm = TRUE)
print(sd_age)

mean_ADHDscore <- mean(dyads_df$ADHDscore, na.rm = TRUE)
print(mean_ADHDscore)
sd_ADHDscore <- sd(dyads_df$ADHDscore, na.rm = TRUE)
print(sd_ADHDscore)

mean_ADHDscoreA <- mean(shared_exp$ADHDscoreA, na.rm = TRUE)
print(mean_ADHDscoreA)
sd_ADHDscoreA <- sd(shared_exp$ADHDscoreA, na.rm = TRUE)
print(sd_ADHDscoreA)

mean_ADHDscoreB <- mean(shared_exp$ADHDscoreB, na.rm = TRUE)
print(mean_ADHDscoreB)
sd_ADHDscoreB <- sd(shared_exp$ADHDscoreB, na.rm = TRUE)
print(sd_ADHDscoreB)

mean_TASscore <- mean(dyads_df$TASscore, na.rm = TRUE)
print(mean_TASscore)
sd_TASscore <- sd(dyads_df$TASscore, na.rm = TRUE)
print(sd_TASscore)

```

